### ISSUE TITLE
No such file or directory: 'data/RobotCar/object/radar/1547122770869274.jpg'

### ISSUE THREAD

**Issue by cxy-ccc** [qiank10/MVDNet#11]
[04/29 15:24:10 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "/home/data/cxy/MVDNet-main/MVDNet/tools/train.py", line 58, in <module>
    args=(args,),
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/home/data/cxy/MVDNet-main/MVDNet/tools/train.py", line 47, in main
    return trainer.train()
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/engine/train_loop.py", line 209, in run_step
    data = next(self._data_loader_iter)
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/data/common.py", line 140, in __iter__
    for d in self.dataset:
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/data/cxy/MVDNet-main/MVDNet/mvdnet/data/robotcar_mapper.py", line 47, in __call__
    radar_intensity = utils.read_image(radar_intensity_name, format='L')
  File "/home/data/cxy/MVDNet-main/detectron2/detectron2/data/detection_utils.py", line 49, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/cxy/anaconda3/envs/MVDNet/lib/python3.7/site-packages/iopath/common/file_io.py", line 612, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: 'data/RobotCar/object/radar/1547122770869274.jpg'
But under the path, the image is already exist.I tried to add a print in front of the line 47 in detection_utils.py, but it can print the right path.

**Comment by cxy-ccc** [comment]
Each time the error occurs, the wrong file is not the same.

**Comment by HBDHBB** [comment]
I have the same issue when trying to train the sample_medium file

**Comment by nililili7876** [comment]
Have you solved it? I have the same problem when training on the medium dataset

**Comment by nujhat-tabassum** [comment]
I am having the same issue. I am eagerly waiting to find the solution to this problem.

**Comment by alirezanjf** [comment]
@nujhat-tabassum  @nililili7876  @HBDHBB  @cxy-ccc 
I'm faced with the same issue, did anyone find the solution??

**Comment by neoskye24** [comment]
SOLVED: you need to update the data_root in the robotcar_mapper python file to your file path.

**Comment by Distrber** [comment]
I checked the radar file and found that the radar image has the .png end, so I just need to change the suffix of the radar file in the mapper file
