### ISSUE TITLE
issue while training 

### ISSUE THREAD

**Issue by AkashSrinivasulu** [qiank10/MVDNet#14]
Hi

Thank you for the wonderful work. I was trying to implement the MVDNet and encountered below error while trying to train MVDNet. I am not sure whether this error is with MVDNet or the torch. Any help is very much appreciated.

Thank you

Config 'MVDNet/configs/train_config.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "D:\Implementation\MVDNet\tools\train.py", line 52, in <module>
    launch(
  File "D:\Implementation\detectron2\detectron2\engine\launch.py", line 62, in launch
    main_func(*args)
  File "D:\Implementation\MVDNet\tools\train.py", line 44, in main
    trainer = Trainer(cfg)
  File "D:\Implementation\detectron2\detectron2\engine\defaults.py", line 310, in __init__
    model = self.build_model(cfg)
  File "D:\Implementation\detectron2\detectron2\engine\defaults.py", line 452, in build_model
    model = build_model(cfg)
  File "D:\Implementation\detectron2\detectron2\modeling\meta_arch\build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File D:\Implementation\mvdnet\mvdnet\modeling\meta_arch\mvdnet.py", line 21, in __init__
    self.backbone = build_backbone(cfg)
  File "D:\Implementation\detectron2\detectron2\modeling\backbone\build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "D:\Implementation\mvdnet\mvdnet\modeling\backbone\mvdnet_backbone.py", line 238, in build_mvdnet_backbone
    radar_backbone = VGG(
  File "D:\Implementation\mvdnet\mvdnet\modeling\backbone\mvdnet_backbone.py", line 54, in __init__
...
    self.out_channels = out_channels
  File "C:/Users/Akash/anaconda3/lib/site-packages/torch/nn/modules/module.py)", line 1317, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute

**Comment by AkashSrinivasulu** [comment]
Dear @qiank10 , 

Can you please elaborate in the ReadMe on the steps after preparing data. I am unable to train the MVDNet as I am not sure how to split the trained data into training and validation sets  and where to place/specify them after preparing the data. Any help is very much appreciated. Thank you.

**Comment by alirezanjf** [comment]
@AkashSrinivasulu 
Hi all. I have been facing the same problem. I solved it by adding two Setter functions for out_channels and stride in the mvdnet_backbone.py file so that you can set these as parameters.

**Comment by Mingsen008** [comment]
> @AkashSrinivasulu Hi all. I have been facing the same problem. I solved it by adding two Setter functions for out_channels and stride in the mvdnet_backbone.py file so that you can set these as parameters.

Hi bro, could you please give a detail description about how to add the two Setter fuctions. Thanks a lot.
